version: 2

updates:
  - package-ecosystem: "bun"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "daily"
      time: "09:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
