#!/usr/bin/env -S bun
import type { Contract as End } from '../../snapshots/c4e4125ec44881fd0f718cbac03cc7eebbcd32205844bb79d5a87b67254c2640/contract';
import endContract from '../../snapshots/c4e4125ec44881fd0f718cbac03cc7eebbcd32205844bb79d5a87b67254c2640/contract.json' with { type: 'json' };
import { Migration, MigrationCLI, col, fn, lit, primaryKey } from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'EarthquakeDeliveryState',
        members: ['PENDING', 'SENT', 'FAILED', 'AMBIGUOUS'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'IncidentSeverity',
        members: ['LOW', 'MEDIUM', 'HIGH'],
      }),
      this.createNativeEnumType({
        schema: 'public',
        typeName: 'IncidentStatus',
        members: ['ACTIVE', 'RESOLVED'],
      }),
      this.createTable({
        schema: 'public',
        table: 'AlertDeliveryClaim',
        columns: [
          col('alertId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('autoCleanup', 'bool', { notNull: true, codecRef: { codecId: 'pg/bool@1' } }),
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('expiresAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('finalized', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('messageId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'AlertDeliveryClaim_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'AlertDestination',
        columns: [
          col('autoCleanup', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('countyId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('latitude', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('longitude', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('radarImageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('snowflake', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('zoneId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'AlertDestination_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Announcement',
        columns: [
          col('body', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('snowflake', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'Announcement_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'AnnouncementDelivery',
        columns: [
          col('announcementId', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('attemptCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('error', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('failedAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('nextAttemptAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('sentAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('subscriptionId', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'AnnouncementDelivery_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'AnnouncementSubscription',
        columns: [
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('updatedAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'AnnouncementSubscription_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'AutoRadarMessage',
        columns: [
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('location', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('messageId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('nextUpdate', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('radarImageUrl', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('radarStation', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('showReflectivity', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('showVelocity', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('snowflake', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updateInterval', 'text', {
            notNull: true,
            default: lit('5m'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('velocityRadarImageUrl', 'text', {
            notNull: true,
            codecRef: { codecId: 'pg/text@1' },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'AutoRadarMessage_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'EarthquakeDelivery',
        columns: [
          col('attemptCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('claimExpiresAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('claimToken', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('deliveredAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('deliveredRevisionAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('error', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('eventId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('failedAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('firstEligibleAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('lastEligible', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('messageId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('nextAttemptAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('state', '"EarthquakeDeliveryState"', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'EarthquakeDeliveryState' } },
          }),
          col('subscriptionId', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('updatedAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'EarthquakeDelivery_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'EarthquakeEvent',
        columns: [
          col('depthKm', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('detailUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('eventTime', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('eventType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('felt', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('firstObservedAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastObservedAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('latitude', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('longitude', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('magnitude', 'float8', { codecRef: { codecId: 'pg/float8@1' } }),
          col('magnitudeType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('place', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('productMetadata', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('significance', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('sourceUpdatedAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('status', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tsunami', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('url', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'EarthquakeEvent_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'EarthquakeIngestionState',
        columns: [
          col('baselinedAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('lastError', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastFailureAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('lastGeneratedAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('lastModified', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastSuccessAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('updatedAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
        ],
        constraints: [primaryKey(['id'], { name: 'EarthquakeIngestionState_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'EarthquakeSubscription',
        columns: [
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('latitude', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('locationName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('longitude', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('minMagnitude', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('radiusKm', 'float8', { notNull: true, codecRef: { codecId: 'pg/float8@1' } }),
          col('snowflake', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'EarthquakeSubscription_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'FeedbackBan',
        columns: [
          col('active', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('reason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('userId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'FeedbackBan_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'ForecastDestination',
        columns: [
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('latitude', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('longitude', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('messageId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('radarImageUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('snowflake', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'ForecastDestination_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'Incident',
        columns: [
          col('autoResolveAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('createdAt', 'timestamptz(3)', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('description', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('key', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('resolvedAt', 'timestamptz(3)', {
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('severity', '"IncidentSeverity"', {
            notNull: true,
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'IncidentSeverity' } },
          }),
          col('snowflake', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', '"IncidentStatus"', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/enum@1', typeParams: { typeName: 'IncidentStatus' } },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'Incident_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'SentAlert',
        columns: [
          col('alertId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('messageId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'SentAlert_pkey' })],
      }),
      this.createTable({
        schema: 'public',
        table: 'VolatileMessage',
        columns: [
          col('channelId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz(3)', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-temporal@1', typeParams: { precision: 3 } },
          }),
          col('guildId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'SERIAL', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('messageId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'], { name: 'VolatileMessage_pkey' })],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AlertDeliveryClaim',
        index: 'AlertDeliveryClaim_alertId_guildId_channelId_key',
        columns: ['alertId', 'guildId', 'channelId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'AlertDeliveryClaim',
        index: 'AlertDeliveryClaim_expiresAt_idx',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AlertDeliveryClaim',
        index: 'AlertDeliveryClaim_finalized_messageId_idx',
        columns: ['finalized', 'messageId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AlertDestination',
        index: 'AlertDestination_expiresAt_idx',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AlertDestination',
        index: 'AlertDestination_guildId_idx',
        columns: ['guildId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AlertDestination',
        index: 'AlertDestination_snowflake_key',
        columns: ['snowflake'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Announcement',
        index: 'Announcement_snowflake_key',
        columns: ['snowflake'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'AnnouncementDelivery',
        index: 'AnnouncementDelivery_announcementId_idx',
        columns: ['announcementId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AnnouncementDelivery',
        index: 'AnnouncementDelivery_announcementId_subscriptionId_key',
        columns: ['announcementId', 'subscriptionId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'AnnouncementDelivery',
        index: 'AnnouncementDelivery_sentAt_nextAttemptAt_idx',
        columns: ['sentAt', 'nextAttemptAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AnnouncementDelivery',
        index: 'AnnouncementDelivery_subscriptionId_idx',
        columns: ['subscriptionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AnnouncementSubscription',
        index: 'AnnouncementSubscription_userId_key',
        columns: ['userId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'AutoRadarMessage',
        index: 'AutoRadarMessage_guildId_nextUpdate_idx',
        columns: ['guildId', 'nextUpdate'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'AutoRadarMessage',
        index: 'AutoRadarMessage_messageId_key',
        columns: ['messageId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'AutoRadarMessage',
        index: 'AutoRadarMessage_snowflake_key',
        columns: ['snowflake'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeDelivery',
        index: 'EarthquakeDelivery_claimExpiresAt_idx',
        columns: ['claimExpiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeDelivery',
        index: 'EarthquakeDelivery_eventId_idx',
        columns: ['eventId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeDelivery',
        index: 'EarthquakeDelivery_messageId_key',
        columns: ['messageId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeDelivery',
        index: 'EarthquakeDelivery_state_nextAttemptAt_idx',
        columns: ['state', 'nextAttemptAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeDelivery',
        index: 'EarthquakeDelivery_subscriptionId_eventId_key',
        columns: ['subscriptionId', 'eventId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeEvent',
        index: 'EarthquakeEvent_eventTime_idx',
        columns: ['eventTime'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeEvent',
        index: 'EarthquakeEvent_lastObservedAt_idx',
        columns: ['lastObservedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeEvent',
        index: 'EarthquakeEvent_magnitude_idx',
        columns: ['magnitude'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeSubscription',
        index: 'EarthquakeSubscription_channelId_idx',
        columns: ['channelId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeSubscription',
        index: 'EarthquakeSubscription_guildId_channelId_latitude_longitude_key',
        columns: ['guildId', 'channelId', 'latitude', 'longitude', 'radiusKm', 'minMagnitude'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeSubscription',
        index: 'EarthquakeSubscription_guildId_idx',
        columns: ['guildId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'EarthquakeSubscription',
        index: 'EarthquakeSubscription_snowflake_key',
        columns: ['snowflake'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'FeedbackBan',
        index: 'FeedbackBan_userId_idx',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'FeedbackBan',
        index: 'FeedbackBan_userId_key',
        columns: ['userId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'ForecastDestination',
        index: 'ForecastDestination_guildId_idx',
        columns: ['guildId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'ForecastDestination',
        index: 'ForecastDestination_messageId_key',
        columns: ['messageId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'ForecastDestination',
        index: 'ForecastDestination_snowflake_key',
        columns: ['snowflake'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Incident',
        index: 'Incident_active_key_key',
        columns: ['key'],
        extras: { where: '(status = \'ACTIVE\'::"IncidentStatus")', unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Incident',
        index: 'Incident_createdAt_idx',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Incident',
        index: 'Incident_severity_idx',
        columns: ['severity'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'Incident',
        index: 'Incident_snowflake_key',
        columns: ['snowflake'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'Incident',
        index: 'Incident_status_idx',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'SentAlert',
        index: 'SentAlert_alertId_guildId_channelId_key',
        columns: ['alertId', 'guildId', 'channelId'],
        extras: { unique: true },
      }),
      this.createIndex({
        schema: 'public',
        table: 'SentAlert',
        index: 'SentAlert_expiresAt_idx',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'SentAlert',
        index: 'SentAlert_guildId_channelId_alertId_idx',
        columns: ['guildId', 'channelId', 'alertId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'VolatileMessage',
        index: 'VolatileMessage_expiresAt_idx',
        columns: ['expiresAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'VolatileMessage',
        index: 'VolatileMessage_messageId_key',
        columns: ['messageId'],
        extras: { unique: true },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'AnnouncementDelivery',
        foreignKey: {
          name: 'AnnouncementDelivery_announcementId_fkey',
          columns: ['announcementId'],
          references: { schema: 'public', table: 'Announcement', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'AnnouncementDelivery',
        foreignKey: {
          name: 'AnnouncementDelivery_subscriptionId_fkey',
          columns: ['subscriptionId'],
          references: { schema: 'public', table: 'AnnouncementSubscription', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'EarthquakeDelivery',
        foreignKey: {
          name: 'EarthquakeDelivery_eventId_fkey',
          columns: ['eventId'],
          references: { schema: 'public', table: 'EarthquakeEvent', columns: ['id'] },
          onDelete: 'restrict',
          onUpdate: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'EarthquakeDelivery',
        foreignKey: {
          name: 'EarthquakeDelivery_subscriptionId_fkey',
          columns: ['subscriptionId'],
          references: { schema: 'public', table: 'EarthquakeSubscription', columns: ['id'] },
          onDelete: 'cascade',
          onUpdate: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
